import { FieldType, defineObject } from 'twenty-sdk/define';

export const LOAN_REQUIREMENT_OBJECT_ID =
  '6b6d0000-1200-4000-8000-000000000001';
export const LOAN_REQUIREMENT_NAME_FIELD_ID =
  '6b6d0000-1200-4000-8000-000000000002';

export default defineObject({
  universalIdentifier: LOAN_REQUIREMENT_OBJECT_ID,
  nameSingular: 'loanRequirement',
  namePlural: 'loanRequirements',
  labelSingular: 'Loan requirement',
  labelPlural: 'Loan requirements',
  description:
    'Loan purpose, requested amount, repayment, and product preference summary.',
  icon: 'IconFileDollar',
  labelIdentifierFieldMetadataUniversalIdentifier: LOAN_REQUIREMENT_NAME_FIELD_ID,
  fields: [
    {
      universalIdentifier: LOAN_REQUIREMENT_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: 'loanName',
      label: 'Loan name',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: '6b6d0000-1200-4000-8000-000000000003',
      type: FieldType.SELECT,
      name: 'loanPurpose',
      label: 'Loan purpose',
      icon: 'IconTarget',
      options: [
        { value: 'PURCHASE_OWNER_OCCUPIED', label: 'Purchase owner occupied', position: 0, color: 'blue' },
        { value: 'PURCHASE_INVESTMENT', label: 'Purchase investment', position: 1, color: 'purple' },
        { value: 'REFINANCE', label: 'Refinance', position: 2, color: 'green' },
        { value: 'CONSTRUCTION', label: 'Construction', position: 3, color: 'orange' },
        { value: 'EQUITY_RELEASE', label: 'Equity release', position: 4, color: 'yellow' },
      ],
    },
    {
      universalIdentifier: '6b6d0000-1200-4000-8000-000000000004',
      type: FieldType.NUMBER,
      name: 'loanAmount',
      label: 'Loan amount',
      icon: 'IconCurrencyDollar',
    },
    {
      universalIdentifier: '6b6d0000-1200-4000-8000-000000000005',
      type: FieldType.SELECT,
      name: 'repaymentType',
      label: 'Repayment type',
      icon: 'IconRepeat',
      options: [
        { value: 'PRINCIPAL_AND_INTEREST', label: 'Principal and interest', position: 0, color: 'green' },
        { value: 'INTEREST_ONLY', label: 'Interest only', position: 1, color: 'orange' },
        { value: 'LINE_OF_CREDIT', label: 'Line of credit', position: 2, color: 'purple' },
      ],
    },
    {
      universalIdentifier: '6b6d0000-1200-4000-8000-000000000006',
      type: FieldType.NUMBER,
      name: 'requestedTermYears',
      label: 'Requested term years',
      icon: 'IconCalendarStats',
    },
    {
      universalIdentifier: '6b6d0000-1200-4000-8000-000000000007',
      type: FieldType.SELECT,
      name: 'loanType',
      label: 'Loan type',
      icon: 'IconHomeDollar',
      options: [
        { value: 'RESIDENTIAL', label: 'Residential', position: 0, color: 'green' },
        { value: 'CONSTRUCTION', label: 'Construction', position: 1, color: 'orange' },
        { value: 'LOW_DOC', label: 'Low doc', position: 2, color: 'purple' },
        { value: 'NON_CONFORMING', label: 'Non conforming', position: 3, color: 'red' },
        { value: 'SMSF', label: 'SMSF', position: 4, color: 'blue' },
      ],
    },
    {
      universalIdentifier: '6b6d0000-1200-4000-8000-000000000008',
      type: FieldType.SELECT,
      name: 'occupancy',
      label: 'Occupancy',
      icon: 'IconHomeCheck',
      options: [
        { value: 'OWNER_OCCUPIED', label: 'Owner occupied', position: 0, color: 'green' },
        { value: 'INVESTMENT', label: 'Investment', position: 1, color: 'purple' },
        { value: 'MIXED', label: 'Mixed', position: 2, color: 'blue' },
      ],
    },
    {
      universalIdentifier: '6b6d0000-1200-4000-8000-000000000009',
      type: FieldType.TEXT,
      name: 'securityState',
      label: 'Security state',
      icon: 'IconMapPin',
    },
    {
      universalIdentifier: '6b6d0000-1200-4000-8000-000000000010',
      type: FieldType.SELECT,
      name: 'ratePreference',
      label: 'Rate preference',
      icon: 'IconPercentage',
      options: [
        { value: 'VARIABLE', label: 'Variable', position: 0, color: 'blue' },
        { value: 'FIXED', label: 'Fixed', position: 1, color: 'purple' },
        { value: 'SPLIT', label: 'Split', position: 2, color: 'green' },
        { value: 'NO_PREFERENCE', label: 'No preference', position: 3, color: 'gray' },
      ],
    },
    {
      universalIdentifier: '6b6d0000-1200-4000-8000-000000000011',
      type: FieldType.BOOLEAN,
      name: 'offsetRequired',
      label: 'Offset required',
      icon: 'IconArrowsExchange',
    },
    {
      universalIdentifier: '6b6d0000-1200-4000-8000-000000000012',
      type: FieldType.BOOLEAN,
      name: 'redrawRequired',
      label: 'Redraw required',
      icon: 'IconRefresh',
    },
    {
      universalIdentifier: '6b6d0000-1200-4000-8000-000000000013',
      type: FieldType.NUMBER,
      name: 'maxAcceptableLvr',
      label: 'Max acceptable LVR',
      icon: 'IconPercentage',
    },
    {
      universalIdentifier: '6b6d0000-1200-4000-8000-000000000014',
      type: FieldType.NUMBER,
      name: 'purchasePrice',
      label: 'Purchase price',
      icon: 'IconCurrencyDollar',
    },
    {
      universalIdentifier: '6b6d0000-1200-4000-8000-000000000015',
      type: FieldType.TEXT,
      name: 'currentLender',
      label: 'Current lender',
      icon: 'IconBuildingBank',
    },
    {
      universalIdentifier: '6b6d0000-1200-4000-8000-000000000016',
      type: FieldType.NUMBER,
      name: 'cashOutAmount',
      label: 'Cash out amount',
      icon: 'IconCash',
    },
    {
      universalIdentifier: '6b6d0000-1200-4000-8000-000000000017',
      type: FieldType.TEXT,
      name: 'mustHaveFeatures',
      label: 'Must-have features',
      icon: 'IconListCheck',
    },
    {
      universalIdentifier: '6b6d0000-1200-4000-8000-000000000018',
      type: FieldType.TEXT,
      name: 'niceToHaveFeatures',
      label: 'Nice-to-have features',
      icon: 'IconListDetails',
    },
    {
      universalIdentifier: '6b6d0000-1200-4000-8000-000000000019',
      type: FieldType.TEXT,
      name: 'customerRequirementsObjectives',
      label: 'Customer requirements/objectives',
      icon: 'IconTargetArrow',
    },
  ],
});
