const mortgageDefaultFilters =
  'Deal Stage, Name, Status, Lender, Loan Amount, Finance Date, Settlement Date, Stage Due Date, Referred By';

const mortgageDefaultColumns =
  'Deal Stage, Name, Application ID, Primary Applicant, Co-Applicant 1, Status, Lender, Lender Reference, Security Property, Loan Amount, Post Cap LVR, Finance Date, Settlement Date, Stage Due Date, Broker Handover Date, Exp. Lodged Date, Lodged w/ FI Date, Pre Approved Date, Formal Approval Date, Exp. Settlement Date, Broker, Assigned Team, Funding Template, Referred By, Lead Source, Created On, Last Note';

const relationshipBoardColumns =
  'Deal Stage, Name, Status, Assigned Team, Broker, Stage Due Date, Lead Source, Created On, Last Note';

const stage = (
  boardType: string,
  stagePosition: number,
  stageName: string,
  stageMapping: string,
  stageDueDays: number | null = null,
  turnAmberDays: number | null = null,
  turnRedDays: number | null = null,
  addStageDueTask = false,
) => ({
  boardType,
  stagePosition,
  stageName,
  stageDueDays,
  turnAmberDays,
  turnRedDays,
  addStageDueTask,
  stageMapping,
});

export const brokerEngineBoardTemplates = [
  {
    boardName: 'Asset Finance',
    boardType: 'ASSET_FINANCE',
    boardStatus: 'ACTIVE',
    sourceSystem: 'BrokerEngine',
    sourceBoardId: '12726',
    collapseEmptyStagesByDefault: true,
    supportsBulkEdit: true,
    supportsListAndKanban: true,
    defaultFilters:
      'Deal Stage, Name, Status, Lender, Loan Amount, Stage Due Date, Broker, Assigned Team, Lead Source',
    defaultColumns: relationshipBoardColumns,
    notes:
      'Observed in BrokerEngine settings. First stage due 3 days, amber 2, red 1.',
  },
  {
    boardName: 'Construction',
    boardType: 'CONSTRUCTION',
    boardStatus: 'ACTIVE',
    sourceSystem: 'BrokerEngine',
    sourceBoardId: '11193',
    collapseEmptyStagesByDefault: true,
    supportsBulkEdit: true,
    supportsListAndKanban: true,
    defaultFilters:
      'Deal Stage, Name, Status, Lender, Loan Amount, Stage Due Date, Broker, Assigned Team, Builder',
    defaultColumns:
      'Deal Stage, Name, Status, Lender, Loan Amount, Stage Due Date, Builder, Broker, Assigned Team, Last Note',
    notes:
      'Observed in BrokerEngine settings. First stage due 30 days, amber 2, red 0.',
  },
  {
    boardName: 'Deal',
    boardType: 'DEAL',
    boardStatus: 'ACTIVE',
    sourceSystem: 'BrokerEngine',
    sourceBoardId: '11191',
    collapseEmptyStagesByDefault: true,
    supportsBulkEdit: true,
    supportsListAndKanban: true,
    defaultFilters: mortgageDefaultFilters,
    defaultColumns: mortgageDefaultColumns,
    notes:
      'Residential mortgage lodgement pipeline. First stage due 4 days, amber 2, red 0.',
  },
  {
    boardName: 'Lead',
    boardType: 'LEAD',
    boardStatus: 'ACTIVE',
    sourceSystem: 'BrokerEngine',
    sourceBoardId: '11190',
    collapseEmptyStagesByDefault: true,
    supportsBulkEdit: true,
    supportsListAndKanban: true,
    defaultFilters: mortgageDefaultFilters,
    defaultColumns:
      'Deal Stage, Name, Application ID, Contact, Status, Lender, Lender Reference, Security Property, Loan Amount, Post Cap LVR, Finance Date, Settlement Date, Stage Due Date, Broker, Assigned Team, Lead Source, Created On, Last Note',
    notes:
      'Residential lead and proposal pipeline. First stage due 1 day, amber 0, red 0.',
  },
  {
    boardName: 'Maintenance',
    boardType: 'MAINTENANCE',
    boardStatus: 'ACTIVE',
    sourceSystem: 'BrokerEngine',
    sourceBoardId: '11192',
    collapseEmptyStagesByDefault: true,
    supportsBulkEdit: true,
    supportsListAndKanban: true,
    defaultFilters:
      'Deal Stage, Name, Status, Lender, Loan Amount, Stage Due Date, Broker, Assigned Team, Review Type',
    defaultColumns: relationshipBoardColumns,
    notes:
      'Observed variation/review board. First stage mapping was Variations; due 3, amber 1, red 0.',
  },
  {
    boardName: 'Partnerships',
    boardType: 'PARTNERSHIPS',
    boardStatus: 'ACTIVE',
    sourceSystem: 'BrokerEngine',
    sourceBoardId: '11396',
    collapseEmptyStagesByDefault: true,
    supportsBulkEdit: true,
    supportsListAndKanban: true,
    defaultFilters:
      'Deal Stage, Name, Status, Referred By, Referrer Manager, Broker, Assigned Team, Stage Due Date',
    defaultColumns: relationshipBoardColumns,
    notes:
      'Observed referral-partner pipeline. First stage due 3, amber 2, red 1, with stage due task enabled.',
  },
  {
    boardName: 'Commercial Lending',
    boardType: 'COMMERCIAL_LENDING',
    boardStatus: 'DRAFT',
    sourceSystem: 'BrokerApp',
    sourceBoardId: 'planned-commercial-lending-v1',
    collapseEmptyStagesByDefault: true,
    supportsBulkEdit: true,
    supportsListAndKanban: true,
    defaultFilters:
      'Deal Stage, Name, Status, Lender, Loan Amount, Security Property, Stage Due Date, Broker, Assigned Team',
    defaultColumns: mortgageDefaultColumns,
    notes:
      'BrokerApp planned board for commercial lending. Confirm stages with broker workflow before activation.',
  },
  {
    boardName: 'Business Lending',
    boardType: 'BUSINESS_LENDING',
    boardStatus: 'DRAFT',
    sourceSystem: 'BrokerApp',
    sourceBoardId: 'planned-business-lending-v1',
    collapseEmptyStagesByDefault: true,
    supportsBulkEdit: true,
    supportsListAndKanban: true,
    defaultFilters:
      'Deal Stage, Name, Status, Lender, Loan Amount, Stage Due Date, Broker, Assigned Team, Lead Source',
    defaultColumns: relationshipBoardColumns,
    notes:
      'BrokerApp planned board for business lending. Confirm stages with broker workflow before activation.',
  },
] as const;

export const brokerEngineStageTemplates = [
  stage('ASSET_FINANCE', 1, 'New Asset Finance Lead', 'ASSET_FINANCE_NEW_LEAD', 3, 2, 1),
  stage('ASSET_FINANCE', 2, 'Attempted Contact 1', 'ASSET_FINANCE_ATTEMPTED_CONTACT_1'),
  stage('ASSET_FINANCE', 3, 'Attempted Contact 2', 'ASSET_FINANCE_ATTEMPTED_CONTACT_2'),
  stage('ASSET_FINANCE', 4, 'Attempted Contact 3', 'ASSET_FINANCE_ATTEMPTED_CONTACT_3'),
  stage('ASSET_FINANCE', 5, 'Initial Call Held', 'ASSET_FINANCE_INITIAL_CALL_HELD'),
  stage('ASSET_FINANCE', 6, 'Referred to Broli', 'ASSET_FINANCE_REFERRED_TO_BROLI'),
  stage('ASSET_FINANCE', 7, 'On Hold', 'ASSET_FINANCE_ON_HOLD'),
  stage('ASSET_FINANCE', 8, 'Settled', 'ASSET_FINANCE_SETTLED'),
  stage('ASSET_FINANCE', 9, 'Lost', 'ASSET_FINANCE_LOST'),
  stage('CONSTRUCTION', 1, 'Letter of Commencement', 'CONSTRUCTION_LETTER_OF_COMMENCEMENT', 30, 2, 0),
  stage('CONSTRUCTION', 2, 'Progress Payment 1', 'CONSTRUCTION_PROGRESS_PAYMENT_1'),
  stage('CONSTRUCTION', 3, 'Progress Payment 2', 'CONSTRUCTION_PROGRESS_PAYMENT_2'),
  stage('CONSTRUCTION', 4, 'Progress Payment 3', 'CONSTRUCTION_PROGRESS_PAYMENT_3'),
  stage('CONSTRUCTION', 5, 'Progress Payment 5', 'CONSTRUCTION_PROGRESS_PAYMENT_5'),
  stage('CONSTRUCTION', 6, 'Progress Payment 4', 'CONSTRUCTION_PROGRESS_PAYMENT_4'),
  stage('CONSTRUCTION', 7, 'Progress Payment 6+', 'CONSTRUCTION_PROGRESS_PAYMENT_6_PLUS'),
  stage('CONSTRUCTION', 8, 'Completion', 'CONSTRUCTION_COMPLETION'),
  stage('DEAL', 1, 'Outstanding Supporting Documents', 'DEAL_OUTSTANDING_SUPPORTING_DOCUMENTS', 4, 2, 0),
  stage('DEAL', 2, 'Prepare for Submission', 'DEAL_PREPARE_FOR_SUBMISSION'),
  stage('DEAL', 3, 'App Docs With Client', 'DEAL_APP_DOCS_WITH_CLIENT'),
  stage('DEAL', 4, 'Signed App Docs Returned', 'DEAL_SIGNED_APP_DOCS_RETURNED'),
  stage('DEAL', 5, 'Application Lodged', 'DEAL_APPLICATION_LODGED'),
  stage('DEAL', 6, 'AIP Issued', 'DEAL_AIP_ISSUED'),
  stage('DEAL', 7, 'AIP > Full Conversion', 'DEAL_AIP_FULL_CONVERSION'),
  stage('DEAL', 8, 'Conditional/MIRs', 'DEAL_CONDITIONAL_MIRS'),
  stage('DEAL', 9, 'Conditions/MIRs With Client', 'DEAL_CONDITIONS_MIRS_WITH_CLIENT'),
  stage('DEAL', 10, 'Conditions/MIRs With Lender', 'DEAL_CONDITIONS_MIRS_WITH_LENDER'),
  stage('DEAL', 11, 'Formal Approval', 'DEAL_FORMAL_APPROVAL'),
  stage('DEAL', 12, 'Mortgage Docs Issued', 'DEAL_MORTGAGE_DOCS_ISSUED'),
  stage('DEAL', 13, 'Mortgage Docs Returned', 'DEAL_MORTGAGE_DOCS_RETURNED'),
  stage('DEAL', 14, 'Ready To Settle', 'DEAL_READY_TO_SETTLE'),
  stage('DEAL', 15, 'Settlement Booked', 'DEAL_SETTLEMENT_BOOKED'),
  stage('DEAL', 16, 'Settlement', 'DEAL_SETTLEMENT'),
  stage('DEAL', 17, 'Lost/Declined', 'DEAL_LOST_DECLINED'),
  stage('LEAD', 1, 'New Lead', 'LEAD_NEW', 1, 0, 0),
  stage('LEAD', 2, 'Attempted Contact 1', 'LEAD_ATTEMPTED_CONTACT_1'),
  stage('LEAD', 3, 'Attempted Contact 2', 'LEAD_ATTEMPTED_CONTACT_2'),
  stage('LEAD', 4, 'Attempted Contact 3', 'LEAD_ATTEMPTED_CONTACT_3'),
  stage('LEAD', 5, 'Initial Call Held > Get Docs', 'LEAD_INITIAL_CALL_GET_DOCS'),
  stage('LEAD', 6, 'Docs Requested', 'LEAD_DOCS_REQUESTED'),
  stage('LEAD', 7, 'Research > Servicing', 'LEAD_RESEARCH_SERVICING'),
  stage('LEAD', 8, 'Prepare Loan Proposal', 'LEAD_PREPARE_LOAN_PROPOSAL'),
  stage('LEAD', 9, 'Loan Proposal Presented', 'LEAD_LOAN_PROPOSAL_PRESENTED'),
  stage('LEAD', 10, 'Client Accepted > Handover', 'LEAD_CLIENT_ACCEPTED_HANDOVER'),
  stage('LEAD', 11, 'On Hold', 'LEAD_ON_HOLD'),
  stage('LEAD', 12, 'Lost Opps', 'LEAD_LOST_OPPS'),
  stage('MAINTENANCE', 1, 'VAR: Request', 'MAINTENANCE_VARIATION_REQUEST', 3, 1, 0),
  stage('MAINTENANCE', 2, 'VAR: Forms Requested', 'MAINTENANCE_VARIATION_FORMS_REQUESTED'),
  stage('MAINTENANCE', 3, 'VAR: Forms sent to client', 'MAINTENANCE_VARIATION_FORMS_SENT_TO_CLIENT'),
  stage('MAINTENANCE', 4, 'VAR: Submitted to lender', 'MAINTENANCE_VARIATION_SUBMITTED_TO_LENDER'),
  stage('MAINTENANCE', 5, 'VAR: Settled', 'MAINTENANCE_VARIATION_SETTLED'),
  stage('PARTNERSHIPS', 1, 'Prospecting', 'PARTNERSHIPS_PROSPECTING', 3, 2, 1, true),
  stage('PARTNERSHIPS', 2, 'Contact Attempt 1', 'PARTNERSHIPS_CONTACT_ATTEMPT_1'),
  stage('PARTNERSHIPS', 3, 'Contact Attempt 2', 'PARTNERSHIPS_CONTACT_ATTEMPT_2'),
  stage('PARTNERSHIPS', 4, 'Contact Attempt 3', 'PARTNERSHIPS_CONTACT_ATTEMPT_3'),
  stage('PARTNERSHIPS', 5, 'Interest Confirmed', 'PARTNERSHIPS_INTEREST_CONFIRMED'),
  stage('PARTNERSHIPS', 6, 'Meeting/Discussion Held', 'PARTNERSHIPS_MEETING_DISCUSSION_HELD'),
  stage('PARTNERSHIPS', 7, 'Agreement in Principle', 'PARTNERSHIPS_AGREEMENT_IN_PRINCIPLE'),
  stage('PARTNERSHIPS', 8, 'Referral Agreement Signed', 'PARTNERSHIPS_REFERRAL_AGREEMENT_SIGNED'),
  stage('PARTNERSHIPS', 9, 'Onboarding/Training', 'PARTNERSHIPS_ONBOARDING_TRAINING'),
  stage('PARTNERSHIPS', 10, 'Lost/Not Interested', 'PARTNERSHIPS_LOST_NOT_INTERESTED'),
  stage('COMMERCIAL_LENDING', 1, 'New Commercial Lending Lead', 'COMMERCIAL_NEW_LEAD', 3, 2, 1),
  stage('COMMERCIAL_LENDING', 2, 'Discovery', 'COMMERCIAL_DISCOVERY'),
  stage('COMMERCIAL_LENDING', 3, 'Docs Requested', 'COMMERCIAL_DOCS_REQUESTED'),
  stage('COMMERCIAL_LENDING', 4, 'Scenario and Servicing', 'COMMERCIAL_SCENARIO_SERVICING'),
  stage('COMMERCIAL_LENDING', 5, 'Prepare Credit Memo', 'COMMERCIAL_PREPARE_CREDIT_MEMO'),
  stage('COMMERCIAL_LENDING', 6, 'Proposal Presented', 'COMMERCIAL_PROPOSAL_PRESENTED'),
  stage('COMMERCIAL_LENDING', 7, 'Client Accepted', 'COMMERCIAL_CLIENT_ACCEPTED'),
  stage('COMMERCIAL_LENDING', 8, 'Lodgement Preparation', 'COMMERCIAL_LODGEMENT_PREPARATION'),
  stage('COMMERCIAL_LENDING', 9, 'Submitted to Lender', 'COMMERCIAL_SUBMITTED_TO_LENDER'),
  stage('COMMERCIAL_LENDING', 10, 'Conditional Approval', 'COMMERCIAL_CONDITIONAL_APPROVAL'),
  stage('COMMERCIAL_LENDING', 11, 'Formal Approval', 'COMMERCIAL_FORMAL_APPROVAL'),
  stage('COMMERCIAL_LENDING', 12, 'Settlement', 'COMMERCIAL_SETTLEMENT'),
  stage('COMMERCIAL_LENDING', 13, 'On Hold', 'COMMERCIAL_ON_HOLD'),
  stage('COMMERCIAL_LENDING', 14, 'Lost/Declined', 'COMMERCIAL_LOST_DECLINED'),
  stage('BUSINESS_LENDING', 1, 'New Business Lending Lead', 'BUSINESS_NEW_LEAD', 3, 2, 1),
  stage('BUSINESS_LENDING', 2, 'Discovery', 'BUSINESS_DISCOVERY'),
  stage('BUSINESS_LENDING', 3, 'Bank Statements and Financials Requested', 'BUSINESS_FINANCIALS_REQUESTED'),
  stage('BUSINESS_LENDING', 4, 'Scenario Assessment', 'BUSINESS_SCENARIO_ASSESSMENT'),
  stage('BUSINESS_LENDING', 5, 'Product and Lender Shortlist', 'BUSINESS_PRODUCT_LENDER_SHORTLIST'),
  stage('BUSINESS_LENDING', 6, 'Proposal Presented', 'BUSINESS_PROPOSAL_PRESENTED'),
  stage('BUSINESS_LENDING', 7, 'Client Accepted', 'BUSINESS_CLIENT_ACCEPTED'),
  stage('BUSINESS_LENDING', 8, 'Application Prepared', 'BUSINESS_APPLICATION_PREPARED'),
  stage('BUSINESS_LENDING', 9, 'Submitted to Lender', 'BUSINESS_SUBMITTED_TO_LENDER'),
  stage('BUSINESS_LENDING', 10, 'Approval Conditions', 'BUSINESS_APPROVAL_CONDITIONS'),
  stage('BUSINESS_LENDING', 11, 'Formal Approval', 'BUSINESS_FORMAL_APPROVAL'),
  stage('BUSINESS_LENDING', 12, 'Settlement', 'BUSINESS_SETTLEMENT'),
  stage('BUSINESS_LENDING', 13, 'Review', 'BUSINESS_REVIEW'),
  stage('BUSINESS_LENDING', 14, 'On Hold', 'BUSINESS_ON_HOLD'),
  stage('BUSINESS_LENDING', 15, 'Lost/Declined', 'BUSINESS_LOST_DECLINED'),
] as const;
