export const brokerEngineDealWorkspaceTools = [
  { workspaceArea: 'OVERVIEW', position: 10, toolName: 'DealDash', toolType: 'PAGE', recordOwner: 'Opportunity dashboard', shownInsideDeal: true },
  { workspaceArea: 'OVERVIEW', position: 20, toolName: 'Team', toolType: 'PAGE', recordOwner: 'Opportunity users and roles', shownInsideDeal: true },
  { workspaceArea: 'OVERVIEW', position: 30, toolName: 'Lender', toolType: 'PAGE', recordOwner: 'Broker lender and selected lender fields', shownInsideDeal: true },
  { workspaceArea: 'OVERVIEW', position: 40, toolName: 'Related Parties', toolType: 'PAGE', recordOwner: 'Contacts, Companies, and applicant profiles', shownInsideDeal: true },

  { workspaceArea: 'FACT_FIND', position: 10, toolName: 'Goals', toolType: 'PAGE', recordOwner: 'Loan requirements and fact-find answers', shownInsideDeal: true },
  { workspaceArea: 'FACT_FIND', position: 20, toolName: 'Applicants', toolType: 'PAGE', recordOwner: 'Applicant profiles and contacts', shownInsideDeal: true },
  { workspaceArea: 'FACT_FIND', position: 30, toolName: 'Dependants', toolType: 'PAGE', recordOwner: 'Fact-find answers and applicant profiles', shownInsideDeal: true },
  { workspaceArea: 'FACT_FIND', position: 40, toolName: 'Assets', toolType: 'PAGE', recordOwner: 'Fact-find answers and serviceability input snapshots', shownInsideDeal: true },
  { workspaceArea: 'FACT_FIND', position: 50, toolName: 'Other Income', toolType: 'PAGE', recordOwner: 'Fact-find answers', shownInsideDeal: true },
  { workspaceArea: 'FACT_FIND', position: 60, toolName: 'Liabilities', toolType: 'PAGE', recordOwner: 'Fact-find answers and serviceability input snapshots', shownInsideDeal: true },
  { workspaceArea: 'FACT_FIND', position: 70, toolName: 'Living Expenses', toolType: 'PAGE', recordOwner: 'Fact-find answers and serviceability input snapshots', shownInsideDeal: true },
  { workspaceArea: 'FACT_FIND', position: 80, toolName: 'Financial Security', toolType: 'PAGE', recordOwner: 'Fact-find answers and compliance notes', shownInsideDeal: true },

  { workspaceArea: 'STRATEGY', position: 10, toolName: 'Interview Guide', toolType: 'PAGE', recordOwner: 'Loan requirements, product search run, and credit proposal notes', shownInsideDeal: true },
  { workspaceArea: 'STRATEGY', position: 20, toolName: 'Security', toolType: 'PAGE', recordOwner: 'Property securities and valuation orders', shownInsideDeal: true },
  { workspaceArea: 'STRATEGY', position: 30, toolName: 'Funding Position', toolType: 'PAGE', recordOwner: 'Serviceability assessments and funding snapshots', shownInsideDeal: true },
  { workspaceArea: 'STRATEGY', position: 40, toolName: 'Products', toolType: 'PAGE', recordOwner: 'Product search runs and product shortlist options', shownInsideDeal: true },
  { workspaceArea: 'STRATEGY', position: 50, toolName: 'Smart Docs', toolType: 'PAGE', recordOwner: 'Broker templates and credit proposals', shownInsideDeal: true },
  { workspaceArea: 'STRATEGY', position: 60, toolName: 'BrokerWizard', toolType: 'WORKFLOW', recordOwner: 'Workflow templates and AI-assisted broker actions', shownInsideDeal: true },

  { workspaceArea: 'LODGEMENT', position: 10, toolName: 'Lodgement Funding', toolType: 'PAGE', recordOwner: 'Funding position and lodgement readiness', shownInsideDeal: true },
  { workspaceArea: 'LODGEMENT', position: 20, toolName: 'Credit Proposal', toolType: 'PAGE', recordOwner: 'Credit proposals', shownInsideDeal: true },
  { workspaceArea: 'LODGEMENT', position: 30, toolName: 'Submission', toolType: 'PAGE', recordOwner: 'Mortgage applications and integration events', shownInsideDeal: true },

  { workspaceArea: 'RIGHT_RAIL', position: 10, toolName: 'Notes', toolType: 'DRAWER', recordOwner: 'Twenty notes and timeline', shownInsideDeal: true },
  { workspaceArea: 'RIGHT_RAIL', position: 20, toolName: 'Checklists', toolType: 'DRAWER', recordOwner: 'Broker templates and tasks', shownInsideDeal: true },
  { workspaceArea: 'RIGHT_RAIL', position: 30, toolName: 'Tasks', toolType: 'DRAWER', recordOwner: 'Twenty tasks', shownInsideDeal: true },
  { workspaceArea: 'RIGHT_RAIL', position: 40, toolName: 'Emails', toolType: 'DRAWER', recordOwner: 'Connected account emails and broker templates', shownInsideDeal: true },
  { workspaceArea: 'RIGHT_RAIL', position: 50, toolName: 'Texts', toolType: 'DRAWER', recordOwner: 'SMS provider events and broker templates', shownInsideDeal: true },
  { workspaceArea: 'RIGHT_RAIL', position: 60, toolName: 'Key Dates', toolType: 'DRAWER', recordOwner: 'Opportunity dates and mortgage application dates', shownInsideDeal: true },
  { workspaceArea: 'RIGHT_RAIL', position: 70, toolName: 'Reports', toolType: 'DRAWER', recordOwner: 'Broker templates and document generation', shownInsideDeal: true },
  { workspaceArea: 'RIGHT_RAIL', position: 80, toolName: '1-Click Workflows', toolType: 'DRAWER', recordOwner: 'Workflow templates', shownInsideDeal: true },
  { workspaceArea: 'RIGHT_RAIL', position: 90, toolName: 'Client Portal', toolType: 'DRAWER', recordOwner: 'Client portal sessions and portal tasks', shownInsideDeal: true },
  { workspaceArea: 'RIGHT_RAIL', position: 100, toolName: 'KYC/CDD', toolType: 'DRAWER', recordOwner: 'KYC/CDD profiles, consents, verification events, AML escalations, and evidence packs', shownInsideDeal: true },

  { workspaceArea: 'BROKER_SETTINGS', position: 10, toolName: 'Lender Details', toolType: 'SETTING', recordOwner: 'Broker lenders', shownInSettings: true },
  { workspaceArea: 'BROKER_SETTINGS', position: 20, toolName: 'Products', toolType: 'SETTING', recordOwner: 'Lender products', shownInSettings: true },
  { workspaceArea: 'BROKER_SETTINGS', position: 30, toolName: 'Packages', toolType: 'SETTING', recordOwner: 'Broker templates and lender products', shownInSettings: true },
  { workspaceArea: 'BROKER_SETTINGS', position: 40, toolName: 'Offers', toolType: 'SETTING', recordOwner: 'Lender products', shownInSettings: true },
  { workspaceArea: 'BROKER_SETTINGS', position: 50, toolName: 'Workflow Templates', toolType: 'SETTING', recordOwner: 'Broker templates', shownInSettings: true },
  { workspaceArea: 'BROKER_SETTINGS', position: 60, toolName: 'Email Templates', toolType: 'SETTING', recordOwner: 'Broker templates', shownInSettings: true },
  { workspaceArea: 'BROKER_SETTINGS', position: 70, toolName: 'Task Templates', toolType: 'SETTING', recordOwner: 'Broker templates', shownInSettings: true },
  { workspaceArea: 'BROKER_SETTINGS', position: 80, toolName: 'SMS Templates', toolType: 'SETTING', recordOwner: 'Broker templates', shownInSettings: true },
  { workspaceArea: 'BROKER_SETTINGS', position: 90, toolName: 'Boards and Stages', toolType: 'SETTING', recordOwner: 'Broker board templates and broker stage templates', shownInSettings: true },
  { workspaceArea: 'BROKER_SETTINGS', position: 100, toolName: 'Fact Find Classic', toolType: 'SETTING', recordOwner: 'Broker form templates', shownInSettings: true },
  { workspaceArea: 'BROKER_SETTINGS', position: 110, toolName: 'Fact Find New', toolType: 'SETTING', recordOwner: 'Broker form templates', shownInSettings: true },
  { workspaceArea: 'BROKER_SETTINGS', position: 120, toolName: 'Loan Smart Docs', toolType: 'SETTING', recordOwner: 'Broker templates', shownInSettings: true },
  { workspaceArea: 'BROKER_SETTINGS', position: 130, toolName: 'Smart Doc Templates', toolType: 'SETTING', recordOwner: 'Broker templates', shownInSettings: true },
  { workspaceArea: 'BROKER_SETTINGS', position: 140, toolName: 'Checklists', toolType: 'SETTING', recordOwner: 'Broker checklist templates, deal checklists, and checklist item templates', shownInSettings: true },
  { workspaceArea: 'BROKER_SETTINGS', position: 150, toolName: 'Client Portal', toolType: 'SETTING', recordOwner: 'Client portal sessions, portal tasks, portal authentication, and safe client-visible status messages', shownInSettings: true },
  { workspaceArea: 'BROKER_SETTINGS', position: 160, toolName: 'AML/CTF and KYC', toolType: 'SETTING', recordOwner: 'KYC/CDD profiles, consents, verification events, AML escalations, evidence packs, and lender rule sets', shownInSettings: true },
  { workspaceArea: 'BROKER_SETTINGS', position: 170, toolName: 'Product Imports', toolType: 'SETTING', recordOwner: 'Product import runs and lender product updates from AFG matrix/API files', shownInSettings: true },
  { workspaceArea: 'BROKER_SETTINGS', position: 180, toolName: 'Integration Providers', toolType: 'SETTING', recordOwner: 'Provider registry for IDV, open banking, product data, lodgement, email, storage, and BrokerEngine compatibility', shownInSettings: true },
  { workspaceArea: 'BROKER_SETTINGS', position: 190, toolName: 'White-label', toolType: 'SETTING', recordOwner: 'Brand, domain, portal, auth, SaaS tenant, and security defaults', shownInSettings: true },
] as const;

export const brokerEngineReportTemplates = [
  '01. Deal Submission Guide',
  '02. Deal (AIP to Full) Cover Sheet',
  '03. Funding Position Report',
  '04. Loan Submission Advice',
  '05. Formal Approval Advice',
  '06. Ready To Settle Advice (with Funding)',
  '07. Authority To Debit/Credit Form',
  '08. Settlement Advice',
  '09. Deal History Report',
] as const;

export const brokerEngineOneClickWorkflowNames = [
  'Lender Rebate',
  'Guarantor Home Loan',
  'Fast Refi',
  'Non-Standard Ownership Structure',
  'Client Lives Overseas',
  'Construction',
  'FIRB',
  'Mat Leave/ Pregnant Pause',
  'Deposit Bond',
  'First Home Owners Grant',
  'Off the Plan',
  'Debt Recycling',
  'Purchasing in a Trust',
  'Rate Lock',
  'Favourable Purchase',
  'Multiple Offset Accounts',
  'Cross Securitisation',
  'Interest in Advance',
  'Refinance',
  'Debt Consolidation',
  'Simultaneous or Prior Settlement',
  'Repayment Type IO vs PI',
  'Split Home Loan',
  'SMSF',
  'LMI Waiver',
  'Low Doc Loan',
  'Bridging Loan',
  'Commercial Loan',
  'Business Loan',
  'Non Face to Face Process Required',
  'Pre-Approval',
  'FHB Stamp Duty Concession',
  'First Home Loan Deposit Scheme (FHLDS/NHG)',
  'Property Insurance Referral (eg, Home and Contents)',
  'Accounting Referral',
  'Financial Planning Referral',
  'Property Management Referral',
  'Property Advisory Referral (eg, Buyers Agent Referral)',
  'Loan Protection Insurance',
  'Equipment Loan',
  'Separation',
  'Equity Release / Cash Out',
  'Self-Employed',
] as const;
